### ISSUE TITLE
Compare MCNP5 and MCNP6 source code

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#160]
Basically perform a diff on the source code and see if that offers any insights.

**Comment by ljacobson64** [comment]
My opinion is that a diff of the source code would probably not provide much insight. The reasons for this are:

1. MCNP6 has a vastly larger number of source files than MCNP5. MCNP5 has 336 source files whereas MCNP6 has 923. (If we only consider files in the `src` directory, MCNP6 has 490.)
2. There are a lot of whitespace changes. MCNP5 did not enforce a strict indent width, switching from 2 to 3 seemingly at random. MCNP6 uses 2 spaces everywhere.
3. Many variable names have changed. For example, the position varialbes in MCNP5 are `xxx`, `yyy`, and `zzz`, while in MCNP6, all the particle state information is stored in the `pbl` structure, and the position variables are `pbl%r%x`, `pbl%r%y`, and `pbl%r%z`.

That being said, it is usually possible to open up the same source files in MCNP5 and MCNP6 and figure out which portions of the code correspond. Most of the MCNP5 code affected by the DAGMC patch looks very similar to the same portions of the MCNP6 code.

**Comment by ljacobson64** [comment]
Here are some of the biggest differences between MCNP5 and MCNP6:

The code handling the MPI calls has been completely rewritten for MCNP6. MCNP5 contains a `dotcomm` directory containing all the MPI subroutines, which are called from `msgcon.F90` and `msgtsk.F90`. MCNP6 does not contain that directory; instead, all the MPI subroutines were written from scratch and added to `messages.F90`.

There have been changes in MCNP's process for reading the input file. MCNP5 reads it twice, first in `pass1.F90` and second in `rdprob.F90`. MCNP6 reads it three times, first in `pass0.F90`, second in `pass1.F90`, and third in `rdprob.F90`. It turns out that the changes made to the MCNP5 version of `pass1.F90` should actually be applied to the MCNP6 version of `pass0.F90`, not `pass1.F90.`

**Comment by 17367119464** [comment]
I'm sorry to disturb you. I'm a student who just started learning MCNP5, but I don't have the source code to learn. Can you share it with me? Thank you very much.

**Comment by makeclean** [comment]
Unfortunately it would be illegal for us to distribute MCNP source code, you can apply for it from https://rsicc.ornl.gov/codes/ccc/ccc8/ccc-850.html
