### ISSUE TITLE
Determine approach for adding DAGMC to MCNP6

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#161]
Following #160....
Determine if and how it will be possible to include DAGMC, especially with the built-in tetmesh capability as a possible control flow competition.

**Comment by ljacobson64** [comment]
My main approach has been to go through the DAGMC patch for MCNP5, open up the relevant sections of the MCNP6 code, and incorporate the changes made in MCNP5 into MCNP6. This is a straightforward process when the code hasn't changed much between the versions, which is the case most of the time. It becomes more difficult when significant changes have occurred between the versions.

The biggest challenge will be integrating DAGMC into the features in MCNP6 not present in MCNP5, such as magnetic field tracking.

**Comment by ljacobson64** [comment]
My current workflow has been run all the MCNP6 test problems (of which there are 1594) through mcnp2cad, editing the input files to match the new cell and surface numbers, and making sure they run properly. This is an arduous process.

So far I haven't experienced any major problems outside of the suite containing the problems with magnetic fields.

**Comment by gonuke** [comment]
Can we get some kind of status bar?  E.g. how many of the 1594 tests have been demonstrated to work?

**Comment by ljacobson64** [comment]
This is going on [here](https://docs.google.com/spreadsheets/d/1Hck8tVe1VwYL0mL1kbyAwd9nH1On1oy-U98w3ZQqJQw/edit#gid=1643125884). Note that the "0" in the "MCNP, Good" column is misleading because I've gotten hundreds of these to work in the past, but I've recently started writing scripts to do more things for me automatically and I haven't re-tested them all yet.

The main bottleneck has been dealing with the fact that the native MCNP cell/surface IDs are not the same as the volume/surface IDs in the faceted geometry. Some of these need to be known when the problem has cell/surface tallies or the source definition contains the cel or surf parameters.

It is often the case that the new volume ID is simply equal to the native cell ID + 1 (because the graveyard is added at the beginning), but this is not guaranteed to be true. Also, the surface IDs are very unpredictable. I haven't yet found a good way to automate this process.

**Comment by ljacobson64** [comment]
#460
