### ISSUE TITLE
System HDF5 on CI

### ISSUE THREAD

**Issue by ljacobson64** [svalinn/DAGMC#608]
We should be testing whether it's possible to build with system HDF5 on CI.

**Comment by ahnaf-tahmid-chowdhury** [comment]
@gonuke, do you have any plans for this, since our CI is building HDF5 from source?

**Comment by gonuke** [comment]
Many stakeholders in our workflow rely on newer versions of HDF5 than many default system HDF5 installations, so I think it's probably fine for us to always specify the version and build it.

That said, our CI Dockerfile does install the system hdf5, so we could develop an option in our testing matrix to use it instead of the built-from-source version.  I'm just not sure how valuable it is.
