### ISSUE TITLE
Review HDF5 dependencies

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#921]
We currently are pegged to a certain HDF5 version for historical reasons, as well as to allow the default ubuntu version.

We should reevaluate our strategy, particularly after #916 has been addressed.

**Comment by ahnaf-tahmid-chowdhury** [comment]
As the latest builds are passing, should we update HDF5 to latest? Please note, MOAB is still set to 5.3.0 as @pshriwise explained us the issue of 5.5.x before.

**Comment by gonuke** [comment]
I think it's worth a PR to use a newer HDF5

**Comment by ahnaf-tahmid-chowdhury** [comment]
I can make a PR. Before that I have a few questions. Do you like to use the latest version of hdf5 1.14.3 from the source? Or want to use the default hdf5 (1.12.1) that comes with Ubuntu (22.04)? If we go with Ubuntu version, are we planning to use the binary version of hdf5 instead of installing from the source?

**Comment by gonuke** [comment]
I think we should build from source with the newest version that works (1.14.3). We used to test with both the default and optionally a newer version, but the default versions are getting to be too old.
